id: P010387
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:12.237932
source_metadata:
  id: bdr:W2CZ5667
  title: འཇིགས་བྱེད་ཀྱི་བསྐྱེད་རྫོགས་ཀྱི་ཁྲིད་ཡིག
  author: ''
  volumes:
    3fa2911e877d4264a2cf9336d98d2123:
      image_group_id: I1KG501
      title: ''
      volume_number: 1
      total_pages: 556
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
