id: IA26D023E
legacy_id: P010387
ocr_import_info:
  bdrc_scan_id: W2CZ5667
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:13:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:56:06.372054+00:00'
last_modified: 2022-09-02 22:56:57.212847
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ5667
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ5667
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇིགས་བྱེད་ཀྱི་བསྐྱེད་རྫོགས་ཀྱི་ཁྲིད་ཡིག
  author: གོ་ཤྲཱི་ཆོས་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5964227978903217
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1KG501:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG501
      total_pages: 556
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG501.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5964227978903217
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
